name: Node.js API Test

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0  # Use a stable MongoDB version
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand({ping: 1})'"
          --health-interval 15s  # Increased interval
          --health-timeout 10s   # Increased timeout
          --health-retries 6      # More retries

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-build-
          ${{ runner.os }}-node-${{ matrix.node-version }}-

    - name: Install dependencies
      run: npm install

    - name: Clean up previous Docker containers
      run: docker container prune -f

    - name: Wait for MongoDB to be ready
      run: |
        echo "Waiting for MongoDB to be ready"
        sleep 60  # Longer wait for MongoDB to be ready

    - name: List all Docker containers
      run: docker ps -a  # List all containers to ensure MongoDB is up

    - name: Show MongoDB logs
      run: |
        echo "MongoDB logs:"
        docker logs $(docker ps -q --filter "ancestor=mongo")  # Fetch logs for mongo container

    - name: Run tests
      env:
        MONGO_URI: mongodb://127.0.0.1:27017/api-db  # Correct URI for MongoDB
      run: npm test
